### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by AndrewWJordan** [BrownUniversity/brown_js_utilities#1]
* Remove leading zeros (date and time)
* Put space between time and AM/PM

~Parse string with date in it  (like formatTimesWithinString does)~

**Comment by adam-at-brown** [comment]
@AndrewWJordan for the date removal of the leading '0' is this for US type only or should this apply to EU and/or INT as well? I am not as familiar with standards for no-US time formats.

**Comment by adam-at-brown** [comment]
@AndrewWJordan for the dates within strings function, what date patterns do you need to cover?

**Comment by AndrewWJordan** [comment]
> @AndrewWJordan for the date removal of the leading '0' is this for US type only or should this apply to EU and/or INT as well? I am not as familiar with standards for no-US time formats.

Neither am I. Best guess 🤷🏻  - I would say that International and Europe date formats should keep the leading zeros. Based on the ISO 8601 format (leading with year format), one of the general principals is "Each date and time value has a fixed number of digits that must be padded with leading zeros." It sounds like Europe adopted that standard as well? 

[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
[EU date/time format](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe)

**Comment by AndrewWJordan** [comment]
> @AndrewWJordan for the dates within strings function, what date patterns do you need to cover?

I am not sure. Could we pass a method the format of the incoming date within the string so that the method knows what to look for? Would that be helpful? It would be hard to cover all the cases otherwise.
